In [ ]:
import torch

In [ ]:
z = torch.zeros(8, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
i = torch.ones((8, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(3, 3)
print('A random tensor:')
print(r1)

r2 = torch.rand(3, 3)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(3, 3)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])

A different random tensor:
tensor([[0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])

Should match r1:
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])


Error is part of example

In [ ]:
ones = torch.ones(3, 4)
print(ones)

twos = torch.ones(3, 4) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # additon allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

r1 = torch.rand(3, 4)
r2 = torch.rand(4, 3)
r3 = r1 + r2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
torch.Size([3, 4])


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
r = torch.rand(4, 4) - 0.5 * 2
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.7641, -0.8021, -0.6673, -0.3854],
        [-0.4001, -0.4987, -0.0603, -0.1344],
        [-0.4793, -0.3135, -0.6386, -0.3507],
        [-0.7367, -0.5238, -0.9452, -0.7976]])

Absolute value of r:
tensor([[0.7641, 0.8021, 0.6673, 0.3854],
        [0.4001, 0.4987, 0.0603, 0.1344],
        [0.4793, 0.3135, 0.6386, 0.3507],
        [0.7367, 0.5238, 0.9452, 0.7976]])

Inverse sine of r:
tensor([[-0.8697, -0.9307, -0.7305, -0.3957],
        [-0.4116, -0.5221, -0.0604, -0.1348],
        [-0.4999, -0.3189, -0.6927, -0.3583],
        [-0.8282, -0.5513, -1.2383, -0.9232]])

Determinant of r:
tensor(-0.0081)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5840, -0.4657, -0.4282, -0.5087],
        [-0.2374, -0.6844,  0.4780,  0.4967],
        [-0.4020,  0.2563, -0.5475,  0.6878],
        [-0.6641,  0.4991,  0.5371, -0.1466]]),
S=tensor([2.2675, 0.5345, 0.1678, 0.0396]),
V=tensor([[ 0.5394,  0.2604,  0.0162, -0.8006],
        [ 0.4678,  0.697